# Generated by Django 5.0.6 on 2026-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_is_super_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
