# Generated by Django 5.0.6 on 2026-08-04 10:49

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("specialty_id", models.UUIDField()),
                (
                    "qualification_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), size=None
                    ),
                ),
                ("requirement_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.JSONField()),
                ("compensation", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("doctors_required", models.IntegerField(default=1)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("URGENT", "Urgent"),
                            ("IMMEDIATE", "Immediate"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospitals.hospitalbranch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_requirements",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "shift_requirements",
            },
        ),
        migrations.CreateModel(
            name="ShiftRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("ACCEPTED_BY_DOCTOR", "Accepted by Doctor"),
                            ("DECLINED_BY_DOCTOR", "Declined by Doctor"),
                            ("CONFIRMED_BY_HOSPITAL", "Confirmed by Hospital"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=30,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_requests",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="shifts.shiftrequirement",
                    ),
                ),
            ],
            options={
                "db_table": "shift_requests",
            },
        ),
        migrations.AddIndex(
            model_name="shiftrequirement",
            index=models.Index(
                fields=["hospital", "status"], name="shift_requi_hospita_ecc197_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shiftrequest",
            unique_together={("requirement", "doctor")},
        ),
    ]
