# Generated by Django 5.0.6 on 2026-08-04 10:49

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cv_file_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("PROFILE_VIEWED", "Profile Viewed"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("INTERVIEW", "Interview"),
                            ("OFFERED", "Offered"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "job_applications",
            },
        ),
        migrations.CreateModel(
            name="ApplicationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20, null=True)),
                ("to_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "db_table": "application_histories",
            },
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("specialty_id", models.UUIDField()),
                (
                    "qualification_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), size=None
                    ),
                ),
                ("description", models.TextField()),
                ("responsibilities", models.TextField(blank=True, null=True)),
                ("requirements", models.TextField(blank=True, null=True)),
                ("location", models.JSONField()),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("ON_REQUEST", "On Request"),
                            ("HIDDEN", "Hidden"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("VISITING", "Visiting"),
                            ("LOCUM", "Locum"),
                            ("CONTRACT", "Contract"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_min_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "experience_max_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("DAY", "Day"),
                            ("NIGHT", "Night"),
                            ("ROTATIONAL", "Rotational"),
                            ("FLEXIBLE", "Flexible"),
                        ],
                        default="DAY",
                        max_length=20,
                    ),
                ),
                (
                    "joining_requirement",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("positions", models.IntegerField(default=1)),
                ("is_urgent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Expired"),
                            ("FILLED", "Filled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closing_date", models.DateTimeField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospitals.hospitalbranch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospitals.hospitaldepartment",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posts",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_posts",
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.jobpost",
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=models.Index(
                fields=["hospital", "status"], name="job_posts_hospita_7471a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=models.Index(
                fields=["specialty_id", "status"], name="job_posts_special_32fa04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "status"], name="job_applica_job_id_e29281_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "doctor")},
        ),
    ]
