# Generated by Django 5.0.6 on 2026-09-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
