# Generated by Django 5.0.6 on 2026-08-04 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "availability_type",
                    models.CharField(
                        choices=[
                            ("LOCUM", "Locum"),
                            ("VISITING", "Visiting"),
                            ("TEMPORARY", "Temporary"),
                            ("PART_TIME", "Part Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("available_from", models.DateField()),
                ("available_until", models.DateField()),
                ("preferred_location", models.JSONField(blank=True, null=True)),
                ("preferred_radius_km", models.IntegerField(blank=True, null=True)),
                (
                    "minimum_compensation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_availabilities",
            },
        ),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_booked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="availability.doctoravailability",
                    ),
                ),
            ],
            options={
                "db_table": "availability_slots",
            },
        ),
        migrations.AddConstraint(
            model_name="availabilityslot",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="slot_end_after_start",
            ),
        ),
    ]
