# Generated by Django 5.0.6 on 2026-09-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_report_evidence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_subscri_cd89af_idx",
            old_name="invoices_subscription_status_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_invoice_58a325_idx",
            old_name="payments_invoice_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_hospita_054729_idx",
            old_name="subscriptions_hospital_status_idx",
        ),
    ]
