# Generated by Django 5.0.6 on 2026-09-19 22:48

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_phase3_models"),
        ("doctors", "0015_add_preferred_language"),
        ("hospitals", "0007_location_point_postgis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="endorsement",
            name="unique_endorsement",
        ),
        migrations.RemoveConstraint(
            model_name="hospitalanalyticssnapshot",
            name="unique_hospital_snapshot_date",
        ),
        migrations.RenameIndex(
            model_name="cmecredit",
            new_name="cme_credits_doctor__89f304_idx",
            old_name="cme_credits_doctor_status_idx",
        ),
        migrations.RenameIndex(
            model_name="endorsement",
            new_name="endorsement_endorse_434247_idx",
            old_name="endorsements_endorsed_skill_idx",
        ),
        migrations.RenameIndex(
            model_name="secondopinionrequest",
            new_name="second_opin_reviewe_84ea71_idx",
            old_name="opinion_reviewer_status_idx",
        ),
        migrations.RenameIndex(
            model_name="telemedicinesession",
            new_name="telemedicin_host_id_9c3270_idx",
            old_name="tele_host_status_idx",
        ),
        migrations.RenameIndex(
            model_name="telemedicinesession",
            new_name="telemedicin_schedul_6d0aab_idx",
            old_name="tele_scheduled_at_idx",
        ),
        migrations.AlterField(
            model_name="cmecredit",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cmeevent",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="endorsement",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="hospitalanalyticssnapshot",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="secondopinionrequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="telemedicinesession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="endorsement",
            unique_together={("endorser", "endorsed", "skill")},
        ),
        migrations.AlterUniqueTogether(
            name="hospitalanalyticssnapshot",
            unique_together={("hospital", "snapshot_date")},
        ),
    ]
