# Generated by Django 5.0.6 on 2026-08-04 10:49

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("photo_file_id", models.UUIDField(blank=True, null=True)),
                ("headline", models.CharField(blank=True, max_length=160, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                ("primary_specialization_id", models.UUIDField(blank=True, null=True)),
                (
                    "clinical_interests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("professional_location", models.JSONField(blank=True, default=dict)),
                (
                    "experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("open_to_opportunities", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="UNVERIFIED",
                        max_length=20,
                    ),
                ),
                (
                    "verification_rejected_reason",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("EVERYONE", "Everyone"),
                            ("DOCTORS_ONLY", "Doctors Only"),
                            ("CONNECTIONS_ONLY", "Connections Only"),
                        ],
                        default="EVERYONE",
                        max_length=20,
                    ),
                ),
                (
                    "career_visibility",
                    models.CharField(
                        choices=[
                            ("VERIFIED_HOSPITALS", "Verified Hospitals"),
                            ("SELECTED_HOSPITALS", "Selected Hospitals"),
                            ("HIDDEN", "Hidden"),
                        ],
                        default="VERIFIED_HOSPITALS",
                        max_length=20,
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doctor_profiles",
            },
        ),
        migrations.CreateModel(
            name="DoctorExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("hospital_name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_experiences",
            },
        ),
        migrations.CreateModel(
            name="DoctorQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("degree", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("file_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_qualifications",
            },
        ),
        migrations.CreateModel(
            name="DoctorRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("council_id", models.UUIDField()),
                ("registration_number", models.CharField(max_length=50)),
                ("registration_year", models.IntegerField()),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doctor_registrations",
                "unique_together": {("council_id", "registration_number")},
            },
        ),
    ]
