# Generated by Django 5.0.6 on 2026-08-12 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0006_postcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="postlike",
            name="liked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liked_posts",
                to="doctors.doctorprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("post", "liked_by")},
        ),
    ]
