# Generated by Django 5.0.6 on 2026-09-19 18:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0011_add_affiliation_follow_block"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="block",
            name="unique_block",
        ),
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique_follow",
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("blocker", "blocked")},
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "following")},
        ),
    ]
