# Generated by Django 5.0.6 on 2026-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospitalfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
