# Generated by Django 5.0.6 on 2026-09-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_logo_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
