# Generated by Django 5.0.6 on 2026-09-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_add_device_token_notification_preference"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="device_toke_user_id_e99165_idx",
            old_name="device_tokens_user_active_idx",
        ),
    ]
